
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int yylineno;

int yylineno = 1;

extern char yytext[];

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng + (yy_more_offset) >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( &yytext[(yy_more_offset)], (yytext_ptr), yyleng + 1 ); \
	yyleng += (yy_more_offset); \
	(yy_prev_more_offset) = (yy_more_offset); \
	(yy_more_offset) = 0; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 46
#define YY_END_OF_BUFFER 47
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[496] =
    {   0,
       47,   46,   28,   46,    1,   46,   46,   27,   46,   27,
       46,   27,   46,   27,   46,   46,   32,   46,   32,   46,
       27,   46,   27,   46,   40,   41,   46,   40,   41,   46,
       40,   41,   46,   40,   41,   46,   40,   41,   46,   40,
       41,   46,   40,   41,   46,   40,   41,   46,   40,   41,
       46,   40,   41,   46,   40,   41,   46,   40,   41,   46,
       40,   41,   46,    2,   46,    2,   28,   46,    2,   46,
        2,   27,   46,    2,   27,   46,    2,   27,   46,    2,
       27,   46,    2,   46,   27,   46,    2,   32,   46,    2,
       32,   46,    2,   27,   46,    2,   27,   46,    2,   40,

       41,   46,    2,   40,   41,   46,    2,   40,   41,   46,
        2,   40,   41,   46,    2,   40,   41,   46,    2,   40,
       41,   46,    2,   40,   41,   46,    2,   40,   41,   46,
        2,   40,   41,   46,    2,   40,   41,   46,    2,   40,
       41,   46,    2,   40,   41,   46,    2,   40,   41,   46,
       28,   24,   23,   40,   32,   13,   14,   40,   41,   40,
       41,   40,   41,   40,   41,   40,   41,   40,   41,   40,
       41,   40,   41,   40,   41,   40,   41,   40,   41,   40,
       41,   40,   41,   40,   41,   40,   41,    2,    2,   28,
        2,    2,    2,    2,   24,    2,   23,    2,    2,   40,

        3,    2,   32,    2,    2,    2,   13,    2,   14,    2,
       40,   41,    2,   40,   41,    2,    2,   40,   41,    2,
       40,   41,    2,   40,   41,    2,   40,   41,    2,   40,
       41,    2,    2,   40,   41,    2,   40,   41,    2,   40,
       41,    2,   40,   41,    2,   40,   41,    2,   40,   41,
        2,   40,   41,    2,   40,   41,   40,   33,   30,   40,
       41,   40,   41,   40,   41,   17,   40,   41,   34,   40,
       41,   18,   34,   40,   41,   19,   40,   41,   16,   40,
       41,   20,   40,   41,   21,   40,   41,   22,   40,   41,
       40,   41,   40,   41,   40,   41,    2,    2,    2,    2,

        2,    2,   40,    3,    2,   33,    2,   30,    2,    2,
        2,    2,   40,   41,    2,   40,   41,    2,   40,   41,
        2,    2,   17,   40,   41,    2,   34,   40,   41,    2,
       18,   34,   40,   41,    2,   19,   40,   41,    2,   16,
       40,   41,    2,   20,   40,   41,    2,   21,   40,   41,
        2,   22,   40,   41,    2,   40,   41,    2,   40,   41,
        2,   40,   41,   45,   42,   37,   40,   41,   40,   41,
       40,   41,   42,   25,   40,   41,   40,   41,   40,   41,
        2,   45,    2,    2,    2,    2,    2,    2,    2,   42,
        2,    2,   37,   40,   41,    2,   40,   41,    2,   40,

       41,    2,    2,   42,    2,   25,   40,   41,    2,   40,
       41,    2,   40,   41,   11,   31,   35,   42,   42,   39,
       40,   41,   38,   40,   41,   15,   40,   41,   26,   40,
       41,    2,    2,    2,   11,    2,   31,    2,    2,   35,
       42,    2,    2,   42,    2,   39,   40,   41,    2,   38,
       40,   41,    2,    2,   15,   40,   41,    2,   26,   40,
       41,   12,    2,    2,   12,    2,    2,   43,    2,    2,
        2,    2,    2,   43,   36,    2,    2,   36,    2,    2,
        2,   29,   44,    2,   29,    2,    2,   44,    4,    7,
        6,    5,    8,   10,    9

    } ;

static yyconst flex_int16_t yy_accept[296] =
    {   0,
        1,    1,    1,    2,    3,    5,    7,    8,   10,   12,
       14,   16,   17,   19,   21,   23,   25,   28,   31,   34,
       37,   40,   43,   46,   49,   52,   55,   58,   61,   64,
       66,   69,   71,   74,   77,   80,   83,   85,   87,   90,
       93,   96,   99,  103,  107,  111,  115,  119,  123,  127,
      131,  135,  139,  143,  147,  151,  152,  152,  152,  152,
      153,  154,  154,  155,  156,  156,  156,  157,  158,  160,
      162,  162,  164,  166,  168,  170,  172,  172,  174,  176,
      178,  180,  182,  184,  186,  188,  189,  191,  192,  193,
      194,  196,  198,  199,  201,  202,  202,  204,  205,  206,

      208,  210,  213,  216,  217,  220,  223,  226,  229,  232,
      233,  236,  239,  242,  245,  248,  251,  254,  257,  257,
      257,  257,  257,  257,  258,  259,  260,  260,  260,  260,
      262,  264,  266,  266,  269,  272,  276,  279,  282,  285,
      288,  291,  293,  295,  297,  298,  299,  300,  301,  302,
      304,  305,  305,  307,  309,  310,  311,  312,  315,  318,
      321,  322,  326,  330,  335,  339,  343,  347,  351,  355,
      358,  361,  364,  365,  365,  365,  365,  365,  365,  365,
      366,  366,  369,  371,  373,  373,  374,  377,  379,  381,
      383,  384,  385,  386,  386,  387,  388,  389,  391,  392,

      396,  399,  402,  403,  405,  409,  412,  415,  415,  415,
      416,  417,  417,  419,  419,  420,  423,  426,  426,  429,
      432,  433,  434,  436,  436,  438,  439,  442,  443,  445,
      449,  453,  454,  458,  462,  462,  463,  463,  463,  464,
      466,  466,  467,  468,  468,  468,  468,  468,  469,  470,
      471,  471,  472,  473,  475,  475,  476,  476,  477,  477,
      477,  479,  480,  480,  480,  481,  481,  481,  481,  481,
      481,  481,  481,  482,  483,  483,  484,  486,  486,  486,
      486,  486,  486,  486,  486,  487,  489,  490,  491,  492,
      493,  494,  495,  496,  496

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    6,    6,    1,    7,
        8,    9,   10,    6,   11,   12,   13,   14,   15,   15,
       15,   16,   17,   18,   18,   18,   18,    6,    6,   19,
        6,   20,    6,    1,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   27,   27,   30,   31,   32,   33,   34,
       27,   35,   36,   37,   38,   27,   27,   39,   27,   27,
       40,    1,   41,    6,   42,    1,   43,   44,   45,   46,

       47,   48,   42,   49,   50,   42,   42,   51,   52,   53,
       54,   55,   42,   56,   42,   57,   42,   58,   59,   60,
       42,   42,    6,    6,    6,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[61] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    4,    4,    4,    4,    4,    1,    1,
        5,    5,    5,    5,    5,    5,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    7,
        1,    6,    5,    5,    5,    5,    5,    5,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6
    } ;

static yyconst flex_int16_t yy_base[307] =
    {   0,
        0,   60,  857,  858,  119,  858,  851,  858,  115,  845,
      843,  841,  110,  115,  833,  831,   99,  101,  107,  810,
      106,  104,  157,  802,  788,  793,   95,  799,   94,    0,
      150,  840,    0,  160,  834,  832,  217,  831,  224,  146,
      822,  820,  284,  325,  120,  804,  124,  133,  353,  791,
      777,  782,  104,  788,  194,  242,  829,  775,  197,  858,
      858,  820,    0,  245,  801,    0,  858,  858,  790,  789,
      250,  788,  216,  240,  237,    0,  284,  767,  292,  770,
      765,  256,  781,  773,  772,    0,  247,  250,  763,  223,
        0,    0,  413,  454,    0,  790,  298,  778,  482,    0,

        0,  747,  236,  332,  243,  252,  288,  285,    0,  337,
      715,  369,  712,  701,  266,  710,  700,  699,  743,  742,
      691,  691,  692,    0,  858,  712,  358,  427,  363,  322,
      303,  323,  434,    0,    0,    0,    0,    0,    0,    0,
        0,  694,  688,  681,  356,  732,  682,  682,  683,  530,
        0,  702,    0,  702,  420,  468,  462,  307,  354,  405,
      473,    0,    0,    0,    0,    0,    0,    0,    0,  684,
      678,  655,  858,  661,  653,  701,  667,  503,  537,  858,
      542,  656,  432,  508,  547,  644,    0,  636,  635,    0,
      631,  622,  670,  655,  639,  558,  575,    0,  580,  633,

      478,  531,  586,  627,    0,  617,  589,  589,  626,  858,
      858,  591,  858,  596,  593,  591,  590,  608,    0,    0,
      582,  612,    0,  580,    0,  624,    0,  629,  547,  551,
      546,  634,    0,    0,  506,  858,  455,  639,  507,    0,
      563,  487,  644,  573,  560,  526,  657,  507,  575,  525,
      548,  483,  672,  472,  467,  858,  677,  457,  593,  641,
        0,  685,  449,  690,  386,  381,  379,  371,  353,  347,
      311,  294,  700,  858,  705,  858,    0,  266,  239,  207,
      164,  156,  152,  144,  710,    0,  858,  858,  858,  858,
      858,  858,  858,  858,  749,  752,  759,  766,  773,  780,

      787,  791,  794,  799,  806,  813
    } ;

static yyconst flex_int16_t yy_def[307] =
    {   0,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  295,  294,  294,  294,  294,  296,  296,  296,  296,
      296,  296,  294,   23,   23,   23,   23,   23,   23,  297,
      297,  297,  297,  297,  297,  297,  298,  299,  297,  297,
      297,  297,  300,  300,   44,   44,   44,   44,   44,   49,
       49,   49,   49,   49,   49,  294,  301,  294,  294,  294,
      294,  295,  302,  294,  294,  303,  294,  294,  296,  296,
      294,  296,  296,  296,  296,   23,  294,   23,   23,   23,
       23,   23,   23,   23,   23,  297,  297,  304,  297,  297,
      297,  297,  298,  305,  306,  294,  297,  297,  297,  297,

      297,   44,   44,  297,   44,   44,   44,   44,   49,  297,
       49,   49,   49,   49,   49,   49,   49,   49,  301,  294,
      294,  294,  294,  302,  294,  303,  294,  294,  294,  296,
      296,  296,  294,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,  304,  297,  297,  297,  297,  305,
      306,  294,  297,   99,  297,  297,  297,   44,   44,   44,
      297,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  296,  296,  296,  294,  294,   23,   23,   23,  297,
      297,  297,  297,  294,  297,  297,  297,  297,  297,   44,

       44,   44,  297,  297,   49,   49,   49,  294,  294,  294,
      294,  294,  294,  294,  294,  296,  296,  294,   23,   23,
      297,  297,  297,  294,  297,  297,  297,  297,  297,   44,
       44,  297,   49,   49,  294,  294,  294,  294,  297,  297,
      294,  297,  297,  294,  294,  294,  294,  294,  297,  297,
      294,  297,  297,  297,  294,  294,  294,  297,  294,  294,
      297,  297,  294,  294,  297,  294,  294,  294,  294,  294,
      294,  294,  297,  294,  294,  294,  297,  294,  294,  294,
      294,  294,  294,  294,  297,  297,  294,  294,  294,  294,
      294,  294,  294,    0,  294,  294,  294,  294,  294,  294,

      294,  294,  294,  294,  294,  294
    } ;

static yyconst flex_int16_t yy_nxt[919] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,    8,    8,   10,
       11,   12,    8,   13,   14,   14,   14,   14,   15,   16,
       17,   18,   19,   20,   20,   20,   20,   20,   21,   22,
       20,   20,   20,   20,   20,   20,   20,   20,   20,    8,
        8,   23,   23,   23,   24,   23,   25,   26,   23,   23,
       23,   27,   23,   23,   23,   28,   23,   23,   29,   23,
       30,   31,    6,   31,   32,   33,   34,   33,   33,   35,
       36,   37,   38,   39,   40,   40,   40,   40,   41,   42,
       43,   44,   45,   46,   46,   46,   46,   46,   47,   48,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   33,

       33,   49,   49,   49,   50,   49,   51,   52,   49,   49,
       49,   53,   49,   49,   49,   54,   49,   49,   55,   49,
       56,   58,   56,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   70,   73,   72,   75,   74,   71,   65,
       71,   81,   84,   71,   65,   71,   71,  106,   82,   85,
      114,   87,   59,   87,  102,  107,  293,  115,  102,   97,
       97,   97,   97,   97,  292,  108,   89,  102,  291,   66,
       76,   76,   76,   76,   76,   98,  290,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   77,   90,   76,   76,

       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   86,   86,  289,
       86,   86,   86,   86,   86,   86,   86,   86,   93,   86,
       86,   86,   86,   86,   86,   86,   86,   97,   97,   97,
       97,   97,  117,   56,  130,   56,  122,  123,   87,  118,
       87,  288,  119,   98,  146,   71,   86,   86,   64,   64,
       64,   64,   64,  128,  128,  128,  128,  128,  131,  132,
      102,  140,  148,  149,   65,  155,   71,  102,  287,   71,
      158,  168,  157,   99,   86,   86,  102,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,  133,  133,  133,

      133,  133,   86,   86,  284,  135,  135,  136,  135,  135,
      141,   97,   97,   97,   97,   97,  159,  160,  103,  102,
      169,  283,  102,  104,   86,   86,   86,   98,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,  137,  183,
      200,  102,   71,   86,   86,  156,  156,  156,  156,  156,
      161,  161,  161,  161,  161,  182,  184,  282,  119,  105,
      146,   71,   71,  281,  104,   86,  109,  109,  109,  109,
      109,  178,  178,  178,  178,  178,  181,  181,  181,  181,
      181,  280,  163,  163,  164,  163,  163,  102,  102,  279,
      201,  278,  110,  277,  109,  109,  109,  109,  109,  109,

      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,   86,   86,  165,   86,   86,   86,   86,
       86,   86,   86,   86,   93,   86,   86,   86,   86,   86,
       86,   86,   86,  196,  196,  196,  196,  196,  202,  102,
      179,  179,  179,  179,  179,  216,  216,  185,  185,  185,
      185,  185,   86,   86,   86,   86,  274,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,  180,  246,  246,
      265,   71,   86,   86,  186,  199,  199,  199,  199,  199,
      263,  197,  197,  197,  197,  197,  203,  203,  203,  203,
      203,  230,  230,   86,   86,  154,  154,  154,  154,  154,

      252,  252,  154,  154,  154,  154,  154,  154,  198,  244,
      249,  262,  102,  204,  245,  250,  212,  212,  212,  212,
      212,  217,  217,  261,  154,  154,  154,  154,  154,  154,
       86,   86,  258,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,  213,  231,  231,  257,   71,   86,   86,
      179,  179,  179,  179,  179,  214,  214,  214,  214,  214,
      185,  185,  185,  185,  185,  102,  256,  255,  259,   86,
       86,  226,  226,  226,  226,  226,  244,  180,  249,  251,
      102,  245,  215,  250,  260,  102,  242,  186,  197,  197,
      197,  197,  197,  228,  228,  228,  228,  228,  227,  203,

      203,  203,  203,  203,  212,  212,  212,  212,  212,  214,
      214,  214,  214,  214,  266,  198,  267,  268,  241,  240,
      229,  238,  238,  238,  238,  238,  204,  239,  269,   71,
       71,  213,  237,  236,  235,  234,  215,  226,  226,  226,
      226,  226,  228,  228,  228,  228,  228,  243,  243,  243,
      243,  243,  247,  247,  247,  247,  247,  253,  253,  253,
      253,  253,  270,  233,  227,  271,  232,  102,  225,  229,
      247,  247,  247,  247,  247,  224,  272,  223,  222,  248,
      221,  220,  219,  218,  254,  253,  253,  253,  253,  253,
      264,  264,  264,  264,  264,   71,  211,  248,  273,  273,

      273,  273,  273,  275,  275,  275,  275,  275,  210,  209,
      208,  207,  254,  285,  285,  285,  285,  285,  275,  275,
      275,  275,  275,  285,  285,  285,  285,  285,  206,  205,
      276,  195,  194,  193,  192,  191,  190,  189,  188,  187,
      286,  177,  176,  175,  174,  276,  173,  120,  172,  171,
      286,   63,  170,   63,   63,   69,   69,   69,   69,   86,
      167,   86,   86,   86,   86,   86,   94,  166,   94,   94,
       94,   94,   94,   95,  162,   95,   95,   95,   95,   95,
      102,  102,  102,  102,  102,  102,  102,  119,  119,  119,
      119,  119,  119,  119,  124,  124,  124,  126,  126,  145,

      145,  145,  145,  145,  145,  145,  150,  153,  150,  150,
      150,  150,  150,  151,  152,  151,  151,  151,  151,  151,
      147,  144,  143,  142,  139,  138,  134,  129,  127,   71,
      125,   62,  121,  120,  116,  113,  112,  111,  102,  101,
      100,   96,   92,   91,   88,   83,   80,   79,   78,   71,
       68,   67,   62,   61,   60,   57,  294,    3,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,

      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294
    } ;

static yyconst flex_int16_t yy_chk[919] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        5,    9,    5,   13,   13,   13,   13,   13,   14,   14,
       14,   14,   14,   17,   19,   18,   22,   21,   17,   13,
       18,   27,   29,   22,   14,   21,   19,   45,   27,   29,
       53,   31,    9,   31,   45,   47,  284,   53,   47,   40,
       40,   40,   40,   40,  283,   48,   34,   48,  282,   13,
       23,   23,   23,   23,   23,   40,  281,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   34,   23,   23,

       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   37,   37,  280,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   39,   39,   39,
       39,   39,   55,   56,   73,   56,   59,   59,   87,   55,
       87,  279,   88,   39,   88,   73,   37,   37,   64,   64,
       64,   64,   64,   71,   71,   71,   71,   71,   74,   75,
      103,   82,   90,   90,   64,  103,   75,  105,  278,   74,
      106,  115,  105,   39,   43,   43,  106,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   77,   77,   77,

       77,   77,   43,   43,  272,   79,   79,   79,   79,   79,
       82,   97,   97,   97,   97,   97,  107,  108,   43,  108,
      115,  271,  107,   43,   43,   44,   44,   97,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   79,  131,
      158,  158,  131,   44,   44,  104,  104,  104,  104,  104,
      110,  110,  110,  110,  110,  130,  132,  270,  145,   44,
      145,  130,  132,  269,   44,   44,   49,   49,   49,   49,
       49,  127,  127,  127,  127,  127,  129,  129,  129,  129,
      129,  268,  112,  112,  112,  112,  112,   49,  159,  267,
      159,  266,   49,  265,   49,   49,   49,   49,   49,   49,

       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   93,   93,  112,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,  155,  155,  155,  155,  155,  160,  160,
      128,  128,  128,  128,  128,  183,  183,  133,  133,  133,
      133,  133,   93,   93,   94,   94,  263,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,  128,  237,  237,
      258,  183,   94,   94,  133,  157,  157,  157,  157,  157,
      255,  156,  156,  156,  156,  156,  161,  161,  161,  161,
      161,  201,  201,   94,   94,   99,   99,   99,   99,   99,

      242,  242,   99,   99,   99,   99,   99,   99,  156,  235,
      239,  254,  201,  161,  235,  239,  178,  178,  178,  178,
      178,  184,  184,  252,   99,   99,   99,   99,   99,   99,
      150,  150,  250,  150,  150,  150,  150,  150,  150,  150,
      150,  150,  150,  178,  202,  202,  248,  184,  150,  150,
      179,  179,  179,  179,  179,  181,  181,  181,  181,  181,
      185,  185,  185,  185,  185,  202,  246,  245,  251,  150,
      150,  196,  196,  196,  196,  196,  244,  179,  249,  241,
      231,  244,  181,  249,  251,  230,  229,  185,  197,  197,
      197,  197,  197,  199,  199,  199,  199,  199,  196,  203,

      203,  203,  203,  203,  212,  212,  212,  212,  212,  214,
      214,  214,  214,  214,  259,  197,  259,  259,  224,  222,
      199,  218,  218,  218,  218,  218,  203,  221,  259,  217,
      216,  212,  215,  209,  208,  207,  214,  226,  226,  226,
      226,  226,  228,  228,  228,  228,  228,  232,  232,  232,
      232,  232,  238,  238,  238,  238,  238,  243,  243,  243,
      243,  243,  260,  206,  226,  260,  204,  200,  195,  228,
      247,  247,  247,  247,  247,  194,  260,  193,  192,  238,
      191,  189,  188,  186,  243,  253,  253,  253,  253,  253,
      257,  257,  257,  257,  257,  182,  177,  247,  262,  262,

      262,  262,  262,  264,  264,  264,  264,  264,  176,  175,
      174,  172,  253,  273,  273,  273,  273,  273,  275,  275,
      275,  275,  275,  285,  285,  285,  285,  285,  171,  170,
      264,  154,  152,  149,  148,  147,  146,  144,  143,  142,
      273,  126,  123,  122,  121,  275,  120,  119,  118,  117,
      285,  295,  116,  295,  295,  296,  296,  296,  296,  297,
      114,  297,  297,  297,  297,  297,  298,  113,  298,  298,
      298,  298,  298,  299,  111,  299,  299,  299,  299,  299,
      300,  102,  300,  300,  300,  300,  300,  301,  301,  301,
      301,  301,  301,  301,  302,  302,  302,  303,  303,  304,

      304,  304,  304,  304,  304,  304,  305,   98,  305,  305,
      305,  305,  305,  306,   96,  306,  306,  306,  306,  306,
       89,   85,   84,   83,   81,   80,   78,   72,   70,   69,
       65,   62,   58,   57,   54,   52,   51,   50,   46,   42,
       41,   38,   36,   35,   32,   28,   26,   25,   24,   20,
       16,   15,   12,   11,   10,    7,    3,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,

      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[47] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 0,     };

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
++(yy_lp); \
goto find_rule; \
}

static int yy_more_offset = 0;
static int yy_prev_more_offset = 0;
#define yymore() ((yy_more_offset) = yy_flex_strlen( yytext ))
#define YY_NEED_STRLEN
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET \
	{ \
	(yy_more_offset) = (yy_prev_more_offset); \
	yyleng -= (yy_more_offset); \
	}
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "conv-c2c.l"
/* EMAX6 Compiler                      */
/*        Copyright (C) 2012 by NAIST. */
/*         Primary writer: Y.Nakashima */
/*                nakashim@is.naist.jp */
/* conv-c2c.l   2012/6/15 */
#line 17 "conv-c2c.l"
double      atof();
void        *malloc();
static int  indx;
#line 861 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 22 "conv-c2c.l"

#line 1048 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 295 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 858 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
					{
					(yy_full_match) = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = (yy_prev_more_offset); yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 23 "conv-c2c.l"
{ ++y_lineno; return(EOL); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 24 "conv-c2c.l"
{ return(ARMV8); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 25 "conv-c2c.l"
{ return(ARMV8); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 26 "conv-c2c.l"
{ return(EMAX6ABEGIN); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 27 "conv-c2c.l"
{ return(EMAX6ASTATEM); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 28 "conv-c2c.l"
{ return(EMAX6AEND); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 29 "conv-c2c.l"
{ return(EMAX6ADRAIN); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 30 "conv-c2c.l"
{ return(EMAX6TBEGIN); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 31 "conv-c2c.l"
{ return(EMAX6TSTATEM); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 32 "conv-c2c.l"
{ return(EMAX6TEND); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 33 "conv-c2c.l"
{ return(CGRA_ULL); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 34 "conv-c2c.l"
{ return(CGRA_UINT); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 35 "conv-c2c.l"
{ return(CGRA_SLL); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 36 "conv-c2c.l"
{ return(CGRA_SRL); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 37 "conv-c2c.l"
{ return(CGRA_WHILE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 38 "conv-c2c.l"
{ return(CGRA_FOR); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 39 "conv-c2c.l"
{ return(CGRA_CEX); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 40 "conv-c2c.l"
{ return(CGRA_EX4); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 41 "conv-c2c.l"
{ return(CGRA_EXE); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 42 "conv-c2c.l"
{ return(CGRA_MEX); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 43 "conv-c2c.l"
{ return(CGRA_MO4); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 44 "conv-c2c.l"
{ return(CGRA_MOP); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 45 "conv-c2c.l"
{
    /* copy "-1LL" --> buf[] */
    yylval = hash_reg_immediate(-1LL);
    return(CGRA_DECR);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 50 "conv-c2c.l"
{ return(CGRA_INCR); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 51 "conv-c2c.l"
{ return(TRAN_READ); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 52 "conv-c2c.l"
{ return(TRAN_WRITE); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 53 "conv-c2c.l"
{ return(*yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 54 "conv-c2c.l"
;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 56 "conv-c2c.l"
{
    /* copy yytext[] --> buf[] */
    for (indx=0; indx<yyleng && indx<BUF_MAXLEN; indx++)
        buf[indx] = yytext[indx];
    buf[indx] = 0;
    if (!hash_search(buf, &yylval)) { /* not found */
      id[yylval].type = T_IMMEDIATE;
      id[yylval].chip = 0;
      id[yylval].cidx = 0;
      id[yylval].val = 0;
    }
    return(IMMEDIATE);
}
	YY_BREAK
case 30:
#line 71 "conv-c2c.l"
case 31:
#line 72 "conv-c2c.l"
case 32:
#line 73 "conv-c2c.l"
case 33:
YY_RULE_SETUP
#line 73 "conv-c2c.l"
{
    /* copy yytext[] --> buf[] */
    for (indx=0; indx<yyleng && indx<BUF_MAXLEN; indx++)
        buf[indx] = yytext[indx];
    buf[indx] = 0;
    if (!hash_search(buf, &yylval)) { /* not found */
      id[yylval].type = T_IMMEDIATE;
      id[yylval].chip = 0;
      id[yylval].cidx = 0;
      id[yylval].val = strtoull(buf, NULL, 0);
    }
    return(IMMEDIATE);
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 87 "conv-c2c.l"
{
    /* copy yytext[] --> buf[] */
    for (indx=0; indx<yyleng && indx<BUF_MAXLEN; indx++)
        buf[indx] = yytext[indx];
    buf[indx] = 0;
    if (!hash_search(buf, &yylval)) { /* not found */
      id[yylval].type = T_EXRNO;
      id[yylval].chip = 0;
      id[yylval].cidx = 0;
      id[yylval].val = strtoull(buf+3, NULL, 0);
    }
    return(EXRNO);
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 101 "conv-c2c.l"
{ /* row only */
    /* copy yytext[] --> buf[] */
    for (indx=0; indx<yyleng && indx<BUF_MAXLEN; indx++)
        buf[indx] = yytext[indx];
    buf[indx] = 0;
    if (!hash_search(buf, &yylval)) { /* not found */
      id[yylval].type = T_ALRNO;
      id[yylval].chip = 0;
      id[yylval].cidx = 0;
      id[yylval].val = strtoull(buf+3, NULL, 0);
    }
    return(ALRNO);
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 115 "conv-c2c.l"
{ /* row+column only */
    /* copy yytext[] --> buf[] */
    for (indx=0; indx<yyleng && indx<BUF_MAXLEN; indx++)
        buf[indx] = yytext[indx];
    buf[indx] = 0;
    if (!hash_search(buf, &yylval)) { /* not found */
      id[yylval].type = T_BDRNO;
      id[yylval].chip = 0;
      id[yylval].cidx = 0;
      id[yylval].val = strtoull(strchr(buf, '\[')+1, NULL, 0)*EMAX_WIDTH+strtoull(strrchr(buf, '\[')+1, NULL, 0);
    }
    return(BDRNO);
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 129 "conv-c2c.l"
{
    /* copy yytext[] --> buf[] */
    for (indx=0; indx<yyleng && indx<BUF_MAXLEN; indx++)
        buf[indx] = yytext[indx];
    buf[indx] = 0;
    if (!hash_search(buf, &yylval)) { /* not found */
      id[yylval].type = T_VARIABLE;
      id[yylval].chip = 1;
      id[yylval].cidx = 0;
      id[yylval].val = 0;
    }
    return(CHIP);
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 143 "conv-c2c.l"
{ /* LOOP[23] not available */
    /* copy yytext[] --> buf[] */
    for (indx=0; indx<yyleng && indx<BUF_MAXLEN; indx++)
        buf[indx] = yytext[indx];
    buf[indx] = 0;
    if (!hash_search(buf, &yylval)) { /* not found */
      id[yylval].type = T_LOOPNO;
      id[yylval].chip = 0;
      id[yylval].cidx = 0;
      id[yylval].val = strtoull(buf+4, NULL, 0);
    }
    return(LOOPNO);
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 157 "conv-c2c.l"
{ /* INIT[23] not available */
    /* copy yytext[] --> buf[] */
    for (indx=0; indx<yyleng && indx<BUF_MAXLEN; indx++)
        buf[indx] = yytext[indx];
    buf[indx] = 0;
    if (!hash_search(buf, &yylval)) { /* not found */
      id[yylval].type = T_INITNO;
      id[yylval].chip = 0;
      id[yylval].cidx = 0;
      id[yylval].val = strtoull(buf+4, NULL, 0);
    }
    return(INITNO);
}
	YY_BREAK
case 40:
#line 172 "conv-c2c.l"
case 41:
#line 173 "conv-c2c.l"
case 42:
#line 174 "conv-c2c.l"
case 43:
#line 175 "conv-c2c.l"
case 44:
YY_RULE_SETUP
#line 175 "conv-c2c.l"
{
    /* copy yytext[] --> buf[] */
    for (indx=0; indx<yyleng && indx<BUF_MAXLEN; indx++)
        buf[indx] = yytext[indx];
    buf[indx] = 0;
    if (!hash_search(buf, &yylval)) { /* not found */
      id[yylval].type = T_VARIABLE;
      id[yylval].chip = 0;
      id[yylval].cidx = 0;
      id[yylval].val  = 0;
    }
    return(VARIABLE);
}
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 189 "conv-c2c.l"
{
    /* copy yytext[] --> buf[] */
    for (indx=0; indx<yyleng && indx<BUF_MAXLEN; indx++)
      buf[indx] = yytext[indx];
    buf[     0] = '(';
    buf[     1] = '(';
    buf[indx-2] = ')';
    buf[indx-1] = ')';
    buf[indx  ] = 0;
    if (!hash_search(buf, &yylval)) { /* not found */
      id[yylval].type = T_ASIS;
      id[yylval].chip = 0;
      id[yylval].cidx = 0;
      id[yylval].val  = 0;
    }
    return(ASIS);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 206 "conv-c2c.l"
ECHO;
	YY_BREAK
#line 1490 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 295 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 295 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 294);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 206 "conv-c2c.l"
