
## EMAX5/6 Application Simulator       ##
##   Copyright (C) 2014 by NAIST UNIV. ##
##         Primary writer: Y.Nakashima ##
##                nakashim@is.naist.jp ##

## -DEMAX5     ... with emaxnc/emax
## -DEMAX6     ... with emaxnc/emax
## -DARMSIML   ... with bsim/csim
## -DARMZYNQ   ... with ZYNQ

## Makefile              native        : none
## Makefile.emax5nc      native+EMAX5NC: -DEMAX5
## Makefile.emax6nc      native+EMAX6NC: -DEMAX6

## Makefile-bsim         bsim          : -DARMSIML
## Makefile-bsim.emax5nc bsim+EMAX5NC  : -DARMSIML -DEMAX5
## Makefile-bsim.emax5   bsim+EMAX5    : -DARMSIML -DEMAX5 emax5_start->emax_start->syscall
## Makefile-zynq.emax5nc(ZYNQ+EMAX5NC  : -DARMZYNQ -DEMAX5)
## Makefile-zynq.emax5  (ZYNQ+EMAX5HW  : -DARMZYNQ -DEMAX5) emax5_start->udev_write

## Makefile-csim         csim          : -DARMSIML
## Makefile-csim.emax6nc csim+EMAX6NC  : -DARMSIML -DEMAX6
## Makefile-csim.emax6   csim+EMAX6    : -DARMSIML -DEMAX6 emax6_start->emax_start->syscall
## Makefile-zynq.emax6nc(ZYNQ+EMAX6NC  : -DARMZYNQ -DEMAX6)
## Makefile-zynq.emax6  (ZYNQ+EMAX6HW  : -DARMZYNQ -DEMAX6) emax6_start->udev_write

PROJTOP	      = ../../
OPTION	      = -mstrict-align -DDEBUG -DCYCLECNT -DARMSIML -DEMAX6 -DFPDDMA
PROGRAM       = test_chipA_div+dma test_chipB_div+dma test_normal_mode+dma
CPP           = aarch64-elf-cpp -P
CC            = aarch64-elf-gcc
CFLAGS        = -I. -O3 -Wno-attributes $(OPTION)
AS            = aarch64-elf-as
ASFLAGS       = 
LD            = aarch64-elf-ld
LDFLAGS       =	-static -M $(PROJTOP)/lib/asim64-lib/_map -L../
LIBS          =	-lgcc -lm -lc -lsparse
LIBFLAGS      = -L$(PROJTOP)/lib/gcc/aarch64-elf/4.8.2/ -L$(PROJTOP)/aarch64-elf/lib/
OBJS	      =	test_chipB_div-emax6.o test_chipA_div-emax6.o test_normal_mode.o 
SRCS          = test_chipB_div-emax6.c test_chipA_div-emax6.c test_normal_mode-emax6.c
LINK_FORMAT   = static
all:		$(PROGRAM)

clean:;		rm -f *.o core *~ *-mark.c *-cppo.c *-emax6.c

test_normal_mode+dma:	test_normal_mode.o
		$(LD) $(LDFLAGS) -o $@ $(PROJTOP)/lib/asim64-lib/_start.o $< $(LIBFLAGS) --start-group $(LIBS) --end-group

test_normal_mode.o: test_normal_mode.c
		$(CC) $(CFLAGS) -c $<

test_chipA_div+dma:	test_chipA_div.o
		$(LD) $(LDFLAGS) -o $@ $(PROJTOP)/lib/asim64-lib/_start.o $< $(LIBFLAGS) --start-group $(LIBS) --end-group

test_chipA_div.o: test_chipA_div.c
		$(CC) $(CFLAGS) -c $<

test_chipB_div+dma:	test_chipB_div.o
		$(LD) $(LDFLAGS) -o $@ $(PROJTOP)/lib/asim64-lib/_start.o $< $(LIBFLAGS) --start-group $(LIBS) --end-group

test_chipB_div.o: test_chipB_div.c
		$(CC) $(CFLAGS) -c $<




ifeq ($(LINK_FORMAT),static)
test_chipA_div.o: $(PROJTOP)/conv-c2c/emax6.h $(PROJTOP)/conv-c2c/emax6lib.c ../Include/emax6_sparselib.h ../libsparse.a
test_chipB_div.o: $(PROJTOP)/conv-c2c/emax6.h $(PROJTOP)/conv-c2c/emax6lib.c ../Include/emax6_sparselib.h ../libsparse.a
endif

ifeq ($(LINK_FORMAT),shared)
test_chipA_div.o: $(PROJTOP)/conv-c2c/emax6.h $(PROJTOP)/conv-c2c/emax6lib.c ../Include/emax6_sparselib.h ../libsparse.so
test_chipB_div.o: $(PROJTOP)/conv-c2c/emax6.h $(PROJTOP)/conv-c2c/emax6lib.c ../Include/emax6_sparselib.h ../libsparse.so
endif