export CPP     = cpp -P
export CC      = gcc
#CFLAGS  = -g3 -O0 -Wall  -msse3 -Wno-unknown-pragmas -funroll-loops -I/usr/local/include -I/usr/include/openblas -DCBLAS_GEMM -DEMAX6 -DDEBUG
CFLAGS  = 
export LDFLAGS = -L/usr/lib64 -L/usr/local/lib -L/usr/lib64/atlas -lm -lrt -lopenblas -lX11 -lXext -lpthread
SUFFIX = .c
EMAX6_SPARSE_TEST = $(wildcard test_*$(SUFFIX)) 
EMAX6_SPARSE_TEST_BIN = $(addprefix ../build_cent/,$(patsubst %.c,%,$(EMAX6_SPARSE_TEST)))
SRCS          =	($(OBJS:.o=.c))
#HEADERS       =	../../src/emax6_sparselib/include/emax6_sparselib.h
INCLUDE = -I../Include
SHARED_LINK = static
SHARED_PATH =



ifeq ($(SHARED_LINK),shared)
	SHARED_PATH=..
	
	EMAX_SPARSE_LIB = -L.. -lsparse
else
	EMAX_SPARSE_LIB = ../build_cent/libsparse.a
endif


all: $(EMAX6_SPARSE_TEST_BIN) 


../build_cent/test_%:	../build_cent/test_%.o libsparse
		$(CC)  $< -o $@  $(EMAX_SPARSE_LIB) $(LDFLAGS) $(CFLAGS)

../build_cent/test_%.o: test_%.c $(HEADERS)
		$(CC) $(CFLAGS)  -c $< ${INCLUDE} -o $@


ifeq ($(SHARED_LINK),shared)
libsparse:	../build_cent/libsparse.so 
else
libsparse:	../build_cent/libsparse.a
endif

clean:  		
	rm -rf *.o *~ $(basename $(PROGRAM))















