CUDA_TOOLKIT := $(shell dirname $$(command -v /usr/local/cuda/bin/nvcc))/..
INC          := -I$(CUDA_TOOLKIT)/include  
ifeq ($(MACHTYPE),x86_64)
LIBS         := -lcublas -lcusparse -arch=sm_80
endif
ifeq ($(MACHTYPE),aarch64)
LIBS         := -lcublas -lcusparse -arch=sm_62
endif
all: test_cu_normal_gemm test_cusparse

test_cu_normal_gemm: test_cu_normal_gemm.cu
	/usr/local/cuda/bin/nvcc $(INC) test_cu_normal_gemm.cu -o test_cu_normal_gemm $(LIBS)

test_cusparse: test_cusparse.cu
	/usr/local/cuda/bin/nvcc $(INC) test_cusparse.cu -o test_cusparse $(LIBS)


.PHONY: clean all test